navikt/fptilbake

- .github/workflows/build.yml
- web/src/main/resources/application-dev-fss-teamforeldrepenger.properties
> Bruker Q2 MQ til å lese kravgrunnlag, slå på sonar scan.

- behandlingskontroll/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandlingskontroll/observer/HistorikkInnslagForAksjonspunkEventObserver.java
Må beholde historikkinnslag som opprettes av BehandlingRest / manuellgjenoppta for å få korrekt kontekst og ident 
Gjør unntak for manuelt gjenopptak her
> TFP-3744 unngå dobbel historikk ved manuelt gjenopptak

- .deploy/fp/dev-fss-teamforeldrepenger.json
- .deploy/fp/prod-fss-teamforeldrepenger.json
- behandlingslager/domene/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandlingslager/behandling/repository/BehandlingRepository.java
- behandlingslager/domene/src/main/java/no/nav/foreldrepenger/tilbakekreving/økonomixml/ØkonomiMottattXmlRepository.java
- behandlingslager/testutilities/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandlingslager/testutilities/kodeverk/ScenarioSimple.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/konfig/ApiConfig.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/forvaltning/ForvaltningKravgrunnlagRestTjeneste.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/forvaltning/ForvaltningTjeneste.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/fpoversikt/FpOversiktDtoTjeneste.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/fpoversikt/FpOversiktRestTjeneste.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/fpoversikt/Sak.java
- web/src/test/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/fpoversikt/FpOversiktDtoTjenesteTest.java
https://github.com/navikt/fp-oversikt/pull/116
> Tjeneste for fpoversikt

- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/behandling/BehandlingRestTjeneste.java
Trengs for å sjekke om fagsak kan avsluttes
> TFP-5553 sjekk om finnes åpen behandling uansett type

- behandlingsprosess/src/test/java/no/nav/foreldrepenger/tilbakekreving/behandling/steg/henleggelse/FellesTestOppsett.java
- behandlingsprosess/src/test/java/no/nav/foreldrepenger/tilbakekreving/behandling/steg/hentgrunnlag/batch/HåndterGamleKravgrunnlagTaskTest.java
- domenetjenester/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandling/impl/BehandlingTjeneste.java
- domenetjenester/src/main/java/no/nav/foreldrepenger/tilbakekreving/fagsak/FagsakTjeneste.java
- domenetjenester/src/test/java/no/nav/foreldrepenger/tilbakekreving/FellesTestOppsett.java
- integrasjontjenester/dokumentbestiller/src/main/java/no/nav/foreldrepenger/tilbakekreving/dokumentbestilling/felles/EksternDataForBrevTjeneste.java
- integrasjontjenester/dokumentbestiller/src/main/java/no/nav/foreldrepenger/tilbakekreving/dokumentbestilling/fritekst/FritekstbrevTjeneste.java
- integrasjontjenester/dokumentbestiller/src/main/java/no/nav/foreldrepenger/tilbakekreving/dokumentbestilling/henleggelse/HenleggelsesbrevTjeneste.java
- integrasjontjenester/dokumentbestiller/src/main/java/no/nav/foreldrepenger/tilbakekreving/dokumentbestilling/innhentdokumentasjon/InnhentDokumentasjonbrevTjeneste.java
- integrasjontjenester/dokumentbestiller/src/main/java/no/nav/foreldrepenger/tilbakekreving/dokumentbestilling/varsel/VarselbrevTjeneste.java
- integrasjontjenester/dokumentbestiller/src/main/java/no/nav/foreldrepenger/tilbakekreving/dokumentbestilling/varsel/manuelt/ManueltVarselBrevTjeneste.java
- integrasjontjenester/dokumentbestiller/src/main/java/no/nav/foreldrepenger/tilbakekreving/dokumentbestilling/vedtak/VedtaksbrevTjeneste.java
- integrasjontjenester/dokumentbestiller/src/test/java/no/nav/foreldrepenger/tilbakekreving/dokumentbestilling/henleggelse/HenleggelsesbrevTjenesteTest.java
- integrasjontjenester/dokumentbestiller/src/test/java/no/nav/foreldrepenger/tilbakekreving/dokumentbestilling/innhentdokumentasjon/InnhentDokumentasjonbrevTjenesteTest.java
- integrasjontjenester/dokumentbestiller/src/test/java/no/nav/foreldrepenger/tilbakekreving/dokumentbestilling/varsel/manuelt/ManueltVarselBrevTjenesteTest.java
- integrasjontjenester/person/src/main/java/no/nav/foreldrepenger/tilbakekreving/domene/person/PersoninfoAdapter.java
- integrasjontjenester/person/src/main/java/no/nav/foreldrepenger/tilbakekreving/domene/person/pdl/AktørTjeneste.java
- pom.xml
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/verge/VergeRestTjeneste.java
For å sende riktig behandlingsnummer
> Propager Ytelsetype ned til PDL

- behandlingsprosess/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandling/steg/beregn/migrer/MigrerBeregningsresultatTask.java
- domenetjenester/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandling/beregning/BeregningResultatPeriode.java
- domenetjenester/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandling/beregning/BeregningsresultatMapper.java
Dersom kun avvik i skatt: Prøver oppdatere beløp i beregningsresultat, lagre og validere på nytt
> Forsøk å patche inn skatt

- behandlingsprosess/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandling/steg/beregn/migrer/MigrerBeregningsresultatTask.java
- domenetjenester/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandling/beregning/BeregningResultat.java
- domenetjenester/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandling/beregning/BeregningResultatPeriode.java
Mer logging til bruk i resttilfelle ved migrering i prod.
> Forberede migrering i prod - logge restavvik siden br forsvinner

- integrasjontjenester/ytelsesvedtak-kafka-poller/src/main/java/no/nav/foreldrepenger/tilbakekreving/hendelser/HendelseHåndtererTjeneste.java
Sett åpen tbk på vent så den ikke behandles før det foreligger oppdatert kravgrunnlag
> Sett åpen tbk på vent ved nytt vedtak

- .github/workflows/deploy-kafka.yml
- pom.xml
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/fordeling/FordelRestTjeneste.java
- web/src/test/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/fordeling/FordelRestTjenesteTest.java
Begynner her der nye koder trengs først
> Nye dokumenttyper/titler

- .deploy/fp/naiserator.yaml
- web/src/main/resources/application-dev-fss-teamforeldrepenger.properties
- web/src/main/resources/application-prod-fss-teamforeldrepenger.properties
- web/src/main/resources/application.properties
Disse sendes ikke lenger til frontend. Dette gjøres i init-fetch til fpsak.
> Vacuum: Rydder ubrukte properties

- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/los/LosBehandlingDtoTjeneste.java
Noe er merkelig med henvisningene for en behandling (42055). Avvik mellom lagret i ekstern_behandling og kravgrunnlag431
> Robust los-håndtering for henlagt tbk

- behandlingslager/domene/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandlingslager/behandling/aksjonspunkt/Venteårsak.java
- behandlingslager/domene/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandlingslager/behandling/repository/BehandlingRepository.java
- behandlingsprosess/src/test/java/no/nav/foreldrepenger/tilbakekreving/behandling/steg/sendvarsel/VarselStegTest.java
- integrasjontjenester/datavarehus/src/main/java/no/nav/foreldrepenger/tilbakekreving/datavarehus/saksstatistikk/BehandlingTilstandTjeneste.java
- integrasjontjenester/datavarehus/src/main/java/no/nav/foreldrepenger/tilbakekreving/datavarehus/saksstatistikk/mapping/BehandlingStatusMapper.java
- integrasjontjenester/datavarehus/src/test/java/no/nav/foreldrepenger/tilbakekreving/datavarehus/saksstatistikk/BehandlingTilstandTjenesteTest.java
- kontrakter/src/main/java/no/nav/foreldrepenger/tilbakekreving/kontrakter/felles/BehandlingStatus.java
- pom.xml
- web/pom.xml
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/forvaltning/ForvaltningBehandlingRestTjeneste.java
- web/src/test/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/forvaltning/ForvaltningBehandlingRestTjenesteTest.java
Etter avklaring med Team Sak. Matcher modell for ventestatus som brukes i fpsak og etterspørres av styringsfolket
@tendestad du får vurdere om K9-tilbake skal sende samme.
> Sender behandlingStatus VENT_type for fptilbake

- pom.xml
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/los/LosBehandlingDtoTjeneste.java
Ingen saksegenskaper fra tilbake. LOS spør sak når det kommer en oppgave
> Forenkle FPLOS-protokoll

- behandlingslager/domene/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandlingslager/varsel/VarselInfo.java
- integrasjontjenester/dokumentbestiller/src/main/java/no/nav/foreldrepenger/tilbakekreving/dokumentbestilling/dto/HentForhåndsvisningVarselbrevDto.java
- integrasjontjenester/fagsystem-klient-api/src/main/java/no/nav/foreldrepenger/tilbakekreving/fagsystem/klient/dto/VarseltekstDto.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/behandling/dto/BestillBrevDto.java
Tillat fritekst i varselbrev opp til 12000 tegn
> Tillat opp til 12000 tegn for varseltekst

- behandlingslager/domene/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandlingslager/varsel/VarselInfo.java
Nødvendig for å forsikre oss om at serialisering og deserialisering fungerer som det skal
> Legg til @lob-annotasjon på varselTekstUtvidet

- behandlingslager/domene/src/main/java/no/nav/foreldrepenger/tilbakekreving/felles/Satser.java
- integrasjontjenester/dokumentbestiller/src/test/resources/vedtaksbrev/FP_ikke_tilbakekreves_med_korrigert_beløp.txt
- integrasjontjenester/dokumentbestiller/src/test/resources/vedtaksbrev/FP_ikke_tilbakekreves_pga_lavt_beløp.txt
Økt satser i henhold til siste justering.
Men: Rettsgebyr-satsen gjelder for "saker innkommet aktuelt år" - dvs er periodisert. Tar en runde med fag om hvordan det skal tolkes i vår sammenheng (periode feilutbetalt, krav oppstått dato, etc)
> TFP-5490 oppdatert rettsgebyr 2025

- behandlingslager/domene/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandlingslager/behandling/automatisksaksbehandling/AutomatiskSaksbehandlingRepository.java
- behandlingslager/domene/src/main/java/no/nav/foreldrepenger/tilbakekreving/felles/Satser.java
- behandlingslager/domene/src/test/java/no/nav/foreldrepenger/tilbakekreving/grunnlag/KravgrunnlagValidatorTest.java
- behandlingslager/testutilities/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandlingslager/testutilities/kodeverk/KravgrunnlagTestBuilder.java
- behandlingsprosess/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandling/steg/automatisksaksbehandling/AutomatiskSaksbehandlingBatchTask.java
- behandlingsprosess/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandling/steg/hentgrunnlag/førstegang/MottattGrunnlagSteg.java
- behandlingsprosess/src/test/java/no/nav/foreldrepenger/tilbakekreving/behandling/steg/automatisksaksbehandling/AutomatiskSaksbehandlingBatchTaskTest.java
- behandlingsprosess/src/test/resources/xml/kravgrunnlag_periode_FEIL_samme_referanse.xml
- behandlingsprosess/src/test/resources/xml/kravgrunnlag_periode_YTEL.xml
- behandlingsprosess/src/test/resources/xml/kravgrunnlag_periode_YTEL_ENDR_samme_referanse.xml
- domenetjenester/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandling/impl/AutomatiskSaksbehandlingVurderingTjeneste.java
- domenetjenester/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandling/impl/KravVedtakStatusTjeneste.java
- domenetjenester/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandling/impl/KravgrunnlagBeregningTjeneste.java
- domenetjenester/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandling/impl/KravgrunnlagTjeneste.java
- domenetjenester/src/test/java/no/nav/foreldrepenger/tilbakekreving/behandling/beregning/TilbakekrevingBeregningTjenesteTest.java
- domenetjenester/src/test/java/no/nav/foreldrepenger/tilbakekreving/behandling/impl/FaktaFeilutbetalingTjenesteTest.java
- domenetjenester/src/test/java/no/nav/foreldrepenger/tilbakekreving/behandling/impl/KravgrunnlagTjenesteTest.java
- integrasjontjenester/datavarehus/src/test/java/no/nav/foreldrepenger/tilbakekreving/datavarehus/saksstatistikk/VedtakOppsummeringTjenesteTest.java
- integrasjontjenester/dokumentbestiller/src/main/java/no/nav/foreldrepenger/tilbakekreving/dokumentbestilling/vedtak/VedtaksbrevTjeneste.java
- integrasjontjenester/dokumentbestiller/src/main/java/no/nav/foreldrepenger/tilbakekreving/dokumentbestilling/vedtak/handlebars/dto/HbKonfigurasjon.java
- integrasjontjenester/dokumentbestiller/src/test/java/no/nav/foreldrepenger/tilbakekreving/dokumentbestilling/DokumentBehandlingTjenesteTest.java
- pom.xml
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/behandling/VilkårsvurderingRestTjeneste.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/forvaltning/HalvtRettsGebyrTask.java
Bruker tidligst av tilbakekreving.opprettetTid og kravgrunnlag.kontrollFelt (typisk ignorer og så kommer det raskt et KG).
Tre steder:
* Utvalg for automatisk saksbehandling
* Vilkårsvurdering
* Brev (4*rettsgebyr) dersom vurdering går rundt småbeløp
> TFP-5944 bruke riktig rettsgebyr

- behandlingslager/domene/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandlingslager/vilkår/InntektskategoriKlassekodeMapper.java
Feil i loggen. Manglende klassekode.
> Manglende mapping for adopsjon frilans

- behandlingslager/domene/src/main/java/no/nav/foreldrepenger/tilbakekreving/felles/Satser.java
Trengs til visning av eldre og avsluttede behandlinger
> Trenger eldre rettsgebyr - visning

- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/server/jetty/abac/k9pdp/XacmlRequestMapper.java
- web/src/test/java/no/nav/foreldrepenger/tilbakekreving/web/server/jetty/abac/k9pdp/PdpKlientImplTest.java
- web/src/test/resources/request.json
- web/src/test/resources/request1.json
- web/src/test/resources/xacml3response.json
- web/src/test/resources/xacmlresponse-array.json
- web/src/test/resources/xacmlresponse.json
- web/src/test/resources/xacmlresponse_1deny_1permit.json
- web/src/test/resources/xacmlresponse_multiple_obligation.json
Det var en N for mye slik at ressurs fagsak ble mappet til "nno.nav". Antar at det er hele problemet.
Tok med en del tester fra fp-felles som ellers vil bli slettet
> TFP-5952 en n for mye i mapping til no.

- integrasjontjenester/dokumentbestiller/src/main/java/no/nav/foreldrepenger/tilbakekreving/dokumentbestilling/innhentdokumentasjon/InnhentDokumentasjonbrevTask.java
- integrasjontjenester/dokumentbestiller/src/main/java/no/nav/foreldrepenger/tilbakekreving/dokumentbestilling/varsel/manuelt/SendManueltVarselbrevTask.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/behandling/BehandlingRestTjeneste.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/behandling/dto/BehandlingDtoTjeneste.java
- web/src/test/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/behandling/dto/BehandlingDtoTjenesteTest.java
Etter ønske utenfra kommer vi til å tilby å kunne sende melding til bruker uten å måtte ta behandling av vent (utenom vanlig autopunkt vent på bruker). 
Hvis K9 vil gå samme veien så er det en mindre endring
> TFP-6002 sende melding til bruker uten å ta av vent

- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/rest/ResourceLink.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/rest/ResourceLinks.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/behandling/BehandlingFaktaRestTjeneste.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/behandling/BehandlingRestTjeneste.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/behandling/BrevRestTjeneste.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/behandling/ForeldelseRestTjeneste.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/behandling/TotrinnskontrollRestTjeneste.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/behandling/VilkårsvurderingRestTjeneste.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/behandling/dto/BehandlingDtoTjeneste.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/behandling/dto/Redirect.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/beregningsresultat/TilbakekrevingResultatRestTjeneste.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/dokument/DokumentRestTjeneste.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/feilutbetaling/FeilutbetalingÅrsakRestTjeneste.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/init/InitielleLinksRestTjeneste.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/tilbakekrevingsgrunnlag/GrunnlagRestTestTjenesteLocalDev.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/verge/VergeRestTjeneste.java
- web/src/test/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/behandling/dto/BehandlingDtoTjenesteTest.java
ingen funksjonelle endringer, bare endringer i navn og slikt
> TFP-5957: refakturer ressurslenker i fptilbake

- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/behandling/BehandlingRestTjeneste.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/behandling/dto/FpsakUuidDto.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/behandling/dto/OpprettBehandlingDto.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/server/jetty/abac/fp/FPPdpRequestBuilder.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/server/jetty/abac/fp/FpPipBehandlingInfo.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/server/jetty/abac/fp/FpsakPipKlient.java
- web/src/test/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/behandling/BehandlingRestTjenesteTest.java
- web/src/test/java/no/nav/foreldrepenger/tilbakekreving/web/server/jetty/FPPdpRequestBuilderTest.java
> TFP-5972 innledende omlegging før ny felles

- behandlingsprosess/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandling/steg/automatiskgjenoppta/GjenopptaBehandlingTjeneste.java
- behandlingsprosess/src/test/java/no/nav/foreldrepenger/tilbakekreving/behandling/steg/automatiskgjenoppta/GjenopptaBehandlingHenleggingTjenesteTest.java
- behandlingsprosess/src/test/java/no/nav/foreldrepenger/tilbakekreving/behandling/steg/automatiskgjenoppta/GjenopptaBehandlingTjenesteTest.java
- behandlingsprosess/src/test/java/no/nav/foreldrepenger/tilbakekreving/behandling/steg/hentgrunnlag/førstegang/MottattGrunnlagStegTest.java
- pom.xml
Bonus: Oppdaterer dependencies
> feat(TFP-6028): Henlegger saker etter passert frist uten kravgrunnlag og med varsel sendt

- domenetjenester/src/main/java/no/nav/foreldrepenger/tilbakekreving/avstemming/batch/AvstemmingSftpBatchTjeneste.java
- domenetjenester/src/main/java/no/nav/foreldrepenger/tilbakekreving/avstemming/forvaltning/AvstemDagTask.java
Trengs for å avstemme dager som ikke ble avstemt pga teknisk feil i k9-tilbake i starten av februar
> Task for at drift kan trigge avstemming for spesifikke dager

- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/behandling/BehandlingRestTjeneste.java
- web/src/test/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/behandling/BehandlingRestTjenesteTest.java
Kunne hente vedtaksinfo for en henlagt tilbakekreving slik at klage kan avvises
> FAGSYSTEM-383285 vedtaksinfo for henlagt TBK til klage

- domenetjenester/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandling/impl/KravgrunnlagBeregningTjeneste.java
- web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/los/LosBehandlingDtoTjeneste.java
Legger til Varsel og Over4RG. Los-PR kommer straks
> TFP-6295 egenskaper for tilbakekreving
