navikt/fptilbake

behandlingsprosess/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandling/steg/automatiskgjenoppta/GjenopptaBehandlingTjeneste.java, web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/forvaltning/ForvaltningKravgrunnlagRestTjeneste.java
Manuell gjenoppta behandling får i dag tilbake callId og polling gir valideringsfeil.
Går over til å returnere taskgruppe slik at polling virker og gjenoppta ikke gir rød strek
=> Returnere taskgruppe slik at polling ikke gir feil

behandlingskontroll/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandlingskontroll/events/BehandlingEnhetEvent.java, integrasjontjenester/los-klient/src/main/java/no/nav/foreldrepenger/tilbakekreving/los/klient/observer/FpLosEventObserver.java, integrasjontjenester/los-klient/src/main/java/no/nav/foreldrepenger/tilbakekreving/los/klient/observer/K9LosEventObserver.java, integrasjontjenester/los-klient/src/main/java/no/nav/foreldrepenger/tilbakekreving/los/klient/task/FpLosPubliserEventTask.java, integrasjontjenester/los-klient/src/main/java/no/nav/foreldrepenger/tilbakekreving/los/klient/task/K9LosPubliserEventTask.java, integrasjontjenester/los-klient/src/test/java/no/nav/foreldrepenger/tilbakekreving/los/klient/observer/FpLosEventObserverTest.java, integrasjontjenester/los-klient/src/test/java/no/nav/foreldrepenger/tilbakekreving/los/klient/observer/K9LosEventObserverTest.java, integrasjontjenester/los-klient/src/test/java/no/nav/foreldrepenger/tilbakekreving/los/klient/task/FpLosPubliserEventTaskAivenTest.java, integrasjontjenester/los-klient/src/test/java/no/nav/foreldrepenger/tilbakekreving/los/klient/task/K9LosPubliserEventTaskAivenTest.java, web/src/test/java/no/nav/foreldrepenger/tilbakekreving/web/server/jetty/AvhengigheterTest.java
Skiller LOS-observer og publiseringtask for FPtilbake og K9tilbake så koden blir greiere.
Legger om til å sende behandling-hendelse slik som fpsak (samme logikk). Trenger at @palfi sjekker at oversikt takler det
Steg2: Forenkle K9LosPubliserEventTask (fjerne fptilbake)
=> TFP-5553 fptilbake sender samme hendelser som fpsak

behandlingsprosess/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandling/steg/beregn/migrer/MigrerBeregningsresultatTask.java, domenetjenester/src/main/java/no/nav/foreldrepenger/tilbakekreving/iverksettevedtak/tjeneste/TilbakekrevingsvedtakTjeneste.java
Vil øke presisjon der perioder kan avvike mellom kravgrunnlag og beregningsresultat - samme diff legges ikke på flere BRperioder.
=> Reiterer utledning av differanse etter patching

domenetjenester/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandling/impl/vilkårsvurdering/AutomatiskVurdertVilkårTjeneste.java, domenetjenester/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandling/impl/vilkårsvurdering/VilkårsvurderingHjelperUtil.java, domenetjenester/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandling/impl/vilkårsvurdering/VilkårsvurderingTjeneste.java
Om en SBH velger å tilbakekreve og velger Grunn Annet og så ombestemmer seg, så vil hele strukturen bli oversendt backend og så lagret som vilkår. 
Dette skaper trøbbel ved iverksetting, ved validering av brevtekster mot perioder.
=> TFP-5671: Ikke lagre særlige grunner om beløpet er under 4R og skal ikke tilbakekreves

integrasjontjenester/pdfgen/pom.xml, integrasjontjenester/pdfgen/src/main/java/no/nav/foreldrepenger/tilbakekreving/pdfgen/PdfGenerator.java, pom.xml, web/src/test/resources/application-vtp-fptilbake.properties
Har testet med autotest lokalt og ting ser egentlig greit ut. 
Det som er interessant er at man ikke får 
`PDType1Font: Using fallback font LiberationSans for base font Helvetica`
melding i loggen.
Så jeg tror at det henger sammen med at `gcr.io/distroless/java21-debian12:nonroot` imaget vi bruker med dokgen ikke har de fontene installert.
=> Bump openHtmlToPdf bibliotek til en fork som faktisk vedlikeholdes.

integrasjontjenester/pdfgen/src/main/java/no/nav/foreldrepenger/tilbakekreving/pdfgen/validering/PdfaValidator.java
Ang bruk av ligaruter og denne [tråden](https://nav-it.slack.com/archives/CEKQHNLLU/p1710317475654249) så blir `ft` tegn transformert til `ɇ` i dokumentet. Dette fører til at 2u validering feiler. 
Vi gjør validering noe mindre restriktiv med 2B men likevel krav oppfyllende.
En mulig løsning er å bytte font. Vi har prøvd med Roboto og NotoSans med gode resultater.
=> Fikser vedtaksbrev utsending

behandlingskontroll/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandlingskontroll/impl/BehandlingskontrollTjeneste.java, domenetjenester/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandling/impl/BehandlingRevurderingTjeneste.java, domenetjenester/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandling/impl/BehandlingTjeneste.java
En del logikk er avhengig av at eksternbehandling er lagret før det sendes statusEvent.
Denne sørger for at ting gjøres mer elegant enn en dobbelevent
=> Consumer for å lagre nødvendigheter etter at behandling er lagret, før event

behandlingslager/domene/src/main/java/no/nav/foreldrepenger/tilbakekreving/behandlingslager/behandling/repository/BehandlingRepository.java, domenetjenester/src/test/java/no/nav/foreldrepenger/tilbakekreving/behandling/impl/FaktaFeilutbetalingTjenesteTest.java, integrasjontjenester/fagsystem-klient-api/src/main/java/no/nav/foreldrepenger/tilbakekreving/fagsystem/klient/Tillegsinformasjon.java, integrasjontjenester/fagsystem-klient-api/src/main/java/no/nav/foreldrepenger/tilbakekreving/fagsystem/klient/dto/SamletEksternBehandlingInfo.java, integrasjontjenester/fagsystem-klient-api/src/main/java/no/nav/foreldrepenger/tilbakekreving/fagsystem/klient/dto/SendtoppdragDto.java, integrasjontjenester/fagsystem-klient-api/src/main/java/no/nav/foreldrepenger/tilbakekreving/fagsystem/klient/dto/TilbakekrevingValgDto.java, integrasjontjenester/fpsak-klient/src/main/java/no/nav/foreldrepenger/tilbakekreving/fpsak/klient/FpsakKlient.java, integrasjontjenester/fpsak-klient/src/test/java/no/nav/foreldrepenger/tilbakekreving/fpsak/klient/FpsakKlientTest.java, integrasjontjenester/k9-sak-klient/src/test/java/no/nav/foreldrepenger/tilbakekreving/k9sak/klient/K9sakKlientTest.java, integrasjontjenester/ytelsesvedtak-kafka-poller/src/main/java/no/nav/foreldrepenger/tilbakekreving/hendelser/HendelseHåndtererTjeneste.java, pom.xml
Vi har regelmessig noen tilfelle av flere raske vedtak med aksjonspunkt i simulering (fx tvillinger med 2 PSB-saker).
TFP-5599 gjør følgende når det finnes en åpen TBK: 
* Valgt TBK uten varsel setter eksisterende på vent (på ny status eller kravgrunnlag). Men bare dersom faktisk sendt oppdrag.
* Valgt TBK med varsel - lagrer eksternbehandling (slik som opprett) og gjør rewind til start. 
Et alternativ til punkt 2 er å henlegge eksisterende TBK-behandling og opprette ny (tilsv Søknad merget og henlagt)
=> TFP-5599 enkleste tilfelle vedtak uten varsel på åpen TBK er noop

web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/beregningsresultat/TilbakekrevingResultatRestTjeneste.java
vurderingsperioder og resultatperioder er ikke nødvendigvis like.
Det er enklest å finne for vurderingsperioder for foreldelse. Her har typisk hele behandlingen en vurderingsperiode. Dersom saksbehandler så splitter vurderingsperioder for vilkårsvurdering, blir det flere resultatperioder for vurderingsperioden for foreldelse.
=> Løsner litt på intern validering i TilbakekrevingResultatRestTjeneste

domenetjenester/src/main/java/no/nav/foreldrepenger/tilbakekreving/historikkv2/HistorikkV2Adapter.java
erstatter kodeverdi i historikkinnslag med kodenavn.
Ny tekst blir: `Hendelse er satt til §14-4 Fakta om svangerskap (Ikke helsefarlig for ventende barn)`
=> TFP-5554: erstatt kodeverdi med kodenavn for HendelseUnderType i HistorikkV2Adapter

integrasjontjenester/dokumentbestiller/src/main/java/no/nav/foreldrepenger/tilbakekreving/dokumentbestilling/dokdist/DokdistKlient.java
Merger og deployer når dokumentløsninger har patchet tilfelle som ikke har blitt distribuert - ellers vil task bare gå til ferdig uten at dokument blir distribuert.
=> Håndtere mulig 409 fra dokdist

web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/forvaltning/ForvaltningBehandlingRestTjeneste.java, web/src/test/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/forvaltning/ForvaltningBehandlingRestTjenesteTest.java
Bakgrunn
Vi har en behandling som står fast i iverksettingsteget med følgende feilmelding fra  oppdragsystemet:  'Innkrevd beløp = 0 ved delvis/full tilbakekreving'. Innkrevd beløp skal være høyere enn 0 her. Lager dette endepunktet for å se hva vi sender over til oppdragssystemet for å finne ut hvor feilen ligger.
=> Forvaltningsendepunkt for å hente vedtak 

pom.xml, web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/server/jetty/abac/AppPepImpl.java, web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/server/jetty/abac/k9pdp/AppPdpConsumerImpl.java, web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/server/jetty/abac/k9pdp/AppPdpKlientImpl.java, web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/server/jetty/abac/k9pdp/XacmlRequestMapper.java, web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/server/jetty/abac/k9pdp/xacml/Advice.java, web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/server/jetty/abac/k9pdp/xacml/Category.java, web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/server/jetty/abac/k9pdp/xacml/Decision.java, web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/server/jetty/abac/k9pdp/xacml/NavFellesAttributter.java, web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/server/jetty/abac/k9pdp/xacml/XacmlRequest.java, web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/server/jetty/abac/k9pdp/xacml/XacmlResponse.java, web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/server/jetty/abac/k9pdp/xacml/XacmlResponseMapper.java
Slår på logging av avvik mellom abac og ny tilgang for fptilbake
Lar k9tilbake kalle klassisk abac. Flytter ut kode fra fp-felles - fase 1. 
Abac/Xacml vil senere utvides med mapping av enums til attributtnavn + at PdpRequestBuilder skilles ut (ny appressursdata)
=> TFP-5952 logge tilgangsdiff flytte ut abac-kode

domenetjenester/src/main/java/no/nav/foreldrepenger/tilbakekreving/iverksettevedtak/tjeneste/TilbakekrevingVedtakPeriodeBeregner.java, domenetjenester/src/test/java/no/nav/foreldrepenger/tilbakekreving/iverksettevedtak.tjeneste/TilbakekrevingVedtakPeriodeBeregnerTest.java
Dette skal fikse et tilfelle hvor iverksettingen feiler i validering i oppdragssystemet: saken har både tilbakekreving av ytelse og feriepenger i samme periode. Det er delvis tilbakekreving, og kun 1 kr feil på feriepengene, og i tilfellet rundes da ned til 0. Når vi sender DELVIS_TILBAKEKREVING (siden vi ser på periode-nivået) feiler valideringen siden 0 ikke passer med DELVIS_TILBAKEKREVING
=> Utleder KodeRestulat fra tilbakekrevingsbeløp isdf periode-nivå

domenetjenester/src/main/java/no/nav/foreldrepenger/tilbakekreving/historikkv2/HistorikkV2Adapter.java
For "sak retur" historikkinnslag.
Før denne endring:
Etter denne endring:
=> historikk: Tydleggjere skille mellom aksjonspunktdefinisjon og beslutning

web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/behandling/dto/BehandlingDto.java, web/src/test/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/behandling/dto/BehandlingDtoTest.java
legger til æøå i 5 props for at vi kan bytte til dem i frontend.
"språkkode" <- "sprakkode"
"behandlingKøet" <-"behandlingKoet"
"venteÅrsakKode" <- "venteArsakKode"
"behandlingPåVent" <- "behandlingPaaVent"
"fristBehandlingPåVent" <- "fristBehandlingPaaVent"
=> legg til æøå i BehandlingDto

integrasjontjenester/pdfgen/pom.xml, pom.xml
Samme versjon som brukes i pdfgen - denne blir aktivt vedlikeholdt. 
Dokgen bør også bruke denne.
=> Bruk en vedlikeholdt versjon av openhtmltopdf

web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/konfig/ApiConfig.java
Ellers får den ikkje effekt, og ObjectMapper resolver blir cacha på tvers av requests.
Oppfølging av #2963
=> Flytt registrering av DynamicJacksonJsonProvider til å vere først.

.github/actions/generate-typescript-client/README.md, .github/actions/generate-typescript-client/action.yaml, .github/workflows/build.yml, .run/web_generate k9-tilbake typescript client.run.xml, .run/web_generate k9-tilbake.openapi.json.run.xml, .run/web_pull openapi-ts-clientmaker-cli.run.xml, web/pom.xml, web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/tjenester/historikk/HistorikkRestTjeneste.java
Ønske om å generere typescript klientkode for kommunikasjon med k9-tilbake server frå k9-sak-web frontend.
Legger inn ny jobb i github workflow. Denne bygger og publiserer typescript klient pakke i github registry, slik at frontend kan bruke denne som dependency. Publisering skjer kun når bygg skjer på master branch.
=> Publish k9 tilbake typescript client

web/pom.xml, web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/jackson/ObjectMapperFactory.java, web/src/main/java/no/nav/foreldrepenger/tilbakekreving/web/app/konfig/ApiConfig.java
Dette medfører betydleg endring i generert openapi spesifikasjon. Versjonsnr aukast derfor til 1.1
Alle typenamn i openapi spesifikasjonen blir no generert med pakkenamn, så ein unngår kollisjoner når typer frå ulike pakker har samme basenamn. Det gjere det og enklare å sjå kvar i serverkjeldekode ein dto type eller enum kjem frå.
Med pakkenamn i typenamnet treng ein ikkje lenger spesialfunksjon for å namngje enum typer basert på property namnet dei er brukt i, sidan ein unngår namnekollisjoner også for disse. Dette gjere det lettare å sjå den direkte koblinga mellom enums i generert openapi spesifikasjon og java kjeldekoden.
For å unngå unødvendig lange typenamn bruker vi ein stripper som fjerner "no.nav.", eller "no.nav.foreldrepenger." viss pakkenamnet starter med dette.
Denne …
=> Oppgrader openapi-spec-utils til versjon 2.
